.TH quikr 1 quikr-2013-05
.SH NAME
quikr \- Calculate estimated frequencies of bacteria in a sample.
.SH SYNOPSIS
.B quikr
.RB [ \-i
.IR input]
.RB [ \-f
.IR sensing-fasta]
.RB [ \-s
.IR sensing-matrix]
.RB [ \-l
.IR lambda ]
.RB [ \-k
.IR kmer ]
.RB [ \-o
.IR output ]
.RB [ \-v ]
.RB [ \-d ]
.P
.BR quikr " ..."
.SH DESCRIPTION
.B quikr
Quikr returns the estimated frequencies of batcteria present when given a
input FASTA file and a trained sensing matrix
.P
.SH OPTIONS
.TP
.B \-i, --input
the sample's fasta file of NGS. READS (fasta format)
.TP
.B \-f, --sensing-fasta
location of the fasta file database used to create the sensing matrix. (fasta format)
.TP
.B \-s, --sensing-matrix
location of the sensing matrix. (trained from quikr_train)
.TP
.B \-k, --kmer
specify what size of kmer to use. (default value is 6)
.TP
.B \-l, --lambda
lambda value to use. (default value is 10000)
.TP
.B \-o, --output
OTU_FRACTION_PRESENT a vector representing the percentage of database sequence's presence in sample. (csv output)
.TP
.B \-v, --verbose
verbose mode.
.TP
.B \-V, --version
print version.
.SH EXAMPLES
Use quikr to calculate the estimated frequencies for sample.fa, using rdp7.fasta as the sensing matrix we generated with quikr_train. This uses 6-mers by default, and a lambda value of 10000:
.P
quikr -i sample.fa -f rdp7.fa -s rdp_sensing_matrix.gz -o frequencies.txt
.SH "SEE ALSO"
\fBmultifasta_to_otu\fP(1), \fBquikr_train\fP(1).
.SH AUTHORS
.B quikr
was written by Gail Rosen <gailr@ece.drexel.edu>, Calvin Morrison 
<mutantturkey@gmail.com>, David Koslicki, Simon Foucart, and Jean-Luc Bouchot.
.SH REPORTING BUGS
.TP
Please report all bugs to Gail Rosen <gailr@ece.drexel.edu>. Include your \
operating system, current compiler, and test files to reproduce your issue.
.SH COPYRIGHT.
Copyright \(co 2013 by Calvin Morrison and Gail Rosen.  Permission to use, 
copy, modify, distribute, and sell this software and its documentation for
any purpose is hereby granted without fee, provided that the above copyright 
notice appear in all copies and that both that copyright notice and this 
permission noticeappear in supporting documentation.  No representations are
made about the suitability of this software for any purpose.  It is provided
"as is" without express or implied warranty.

